name: doctor_h_appointments_app
description: "Doctor H Appointments App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.14 # Add the flutter_native_splash dependency

flutter:
  uses-material-design: true

  # Adding custom fonts here
  fonts:
    - family: Museo Sans
      fonts:
        - asset: assets/fonts/fonnts.com-Museo_Sans_100.otf
          weight: 100
        - asset: assets/fonts/fonnts.com-Museo_Sans_100_Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/fonnts.com-Museo_Sans_300.otf
          weight: 300
        - asset: assets/fonts/fonnts.com-Museo_Sans_300_Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/fonnts.com-Museo_Sans_500.otf
          weight: 500
        - asset: assets/fonts/fonnts.com-Museo_Sans_500_Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/fonnts.com-Museo_Sans_700.otf
          weight: 700
        - asset: assets/fonts/fonnts.com-Museo_Sans_700_Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/fonnts.com-Museo_Sans_900.otf
          weight: 900
        - asset: assets/fonts/fonnts.com-Museo_Sans_900_Italic.otf
          weight: 900
          style: italic

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/
    - lib/shared/widgets/

flutter_native_splash:
  color: "#000000" # Background color of the splash screen
  image: /Users/mohammedmahmoud/StudioProjects/doctor_h_appointments_app/assets/images/splash/splash.png # Path to your splash image
